# Darius-Florentin Neatu <neatudarius@gmail.com>

# Exemplu de Makefile pentru tema

# tag-uri obligatorii (nume + comportament identic)
# build    => compileaza toata tema
#             (ATENTIE! E important - NU compilati in tag-urile de run. Sesizati?)
# run-p$ID => ruleaza problema cu ID-ul specificat (1, 2, 3, 4)
# clean    => sterge toate fisierele generate

# restul este la alegerea studentului
# TODO

# nume necesar (build)
build:
	g++ crypto.cpp -o crypto
	g++ stocks.cpp -o stocks
	g++ valley.cpp -o valley
	g++ ridge.cpp -o ridge
	g++ trigigel.cpp -o trigigel

run-p1: crypto     # nume necesar
	./crypto

run-p2: stocks     # nume necesar
	./stocks

run-p3: valley     # nume necesar
	./valley

run-p4: ridge     # nume necesar
	./ridge

run-p5: trigigel     # nume necesar
	./trigigel

clean:		 # nume necesar
	rm -f crypto stocks valley ridge trigigel
