# Darius-Florentin Neatu <neatudarius@gmail.com>

build:
	g++ -g ./src/poduri.cpp -o poduri
	g++ -g ./src/adrese.cpp -o adrese
	g++ -g ./src/lego.cpp -o lego
	g++ -g ./src/retea.cpp -o retea

run-p1: poduri
	./poduri

run-p2: adrese
	./adrese

run-p3: lego
	./lego

run-p4: retea
	./retea

clean:
	rm -f poduri adrese lego retea